apiVersion: v1
kind: Service
metadata:
   name: k8-service-dummy
spec:
  ports:
    - name: 90-8081
      port: 90
      protocol: TCP
      targetPort: 8081
  selector:
    app: k8-service-dummy
  type: NodePort
